### ISSUE TITLE
How could I help?

### ISSUE THREAD

**Issue by Minozzzi** [JasonFritsche/motivationalCats#88]
I really liked the repository and found it a very fun idea, I would like to contribute something

**Comment by JasonFritsche** [comment]
Hello @Minozzzi , thank you for your interest in this project. You're more than welcome to contribute in any way that you see fit. I believe there's only one real issue at the moment, and that has been taken by another contributor. That being said, please feel free to change any styles/theme, header font, font in general, add animations/transitions, etc. There is one "issue" I can think of, and that is how size of the image affects the size of the card. If you'd like, you could figure out a way to have a max-height for the image so that the card never changes in size.

**Comment by Minozzzi** [comment]
Alright, I will try to make this improvement
